version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
      - '443:443'
    links:
      - mongo
    depends_on:
      - mongo



  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'
     
